// Generated by BUCKLESCRIPT VERSION 3.1.0, PLEASE EDIT WITH CARE


function stateToJs(param) {
  return {
          ticks: param[/* ticks */0],
          data: param[/* data */1]
        };
}

function stateFromJs(param) {
  return /* record */[
          /* ticks */param.ticks,
          /* data */param.data
        ];
}

var initialState = /* record */[
  /* ticks */0,
  /* data : Idle */0
];

function $$default(state, action) {
  if (state == null) {
    return initialState;
  } else if (action.tag) {
    return /* record */[
            /* ticks */state[/* ticks */0],
            /* data */action[0]
          ];
  } else {
    return /* record */[
            /* ticks */state[/* ticks */0] + 1 | 0,
            /* data */state[/* data */1]
          ];
  }
}

export {
  stateToJs ,
  stateFromJs ,
  initialState ,
  $$default ,
  $$default as default,
  
}
/* No side effect */
